// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: PERes.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace PERes
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ResSkillList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"lst")]
        public global::System.Collections.Generic.List<ResSkill> Lsts { get; } = new global::System.Collections.Generic.List<ResSkill>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResSkill : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ID", IsRequired = true)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"damagetype", IsRequired = true)]
        public int Damagetype { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"cooldown")]
        public int[] Cooldowns { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"des", IsRequired = true)]
        public string Des { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResFubenList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"lst")]
        public global::System.Collections.Generic.List<ResFuben> Lsts { get; } = new global::System.Collections.Generic.List<ResFuben>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResFuben : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ID", IsRequired = true)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"type", IsRequired = true)]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"mapid", IsRequired = true)]
        public int Mapid { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"drop")]
        public global::System.Collections.Generic.List<DropItem> Drops { get; } = new global::System.Collections.Generic.List<DropItem>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DropItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"num", IsRequired = true)]
        public int Num { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResGoodsList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"lst")]
        public global::System.Collections.Generic.List<ResGoods> Lsts { get; } = new global::System.Collections.Generic.List<ResGoods>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResGoods : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ID", IsRequired = true)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"type", IsRequired = true)]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"des", IsRequired = true)]
        public string Des { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
